name: Arora

channels:
  - conda-forge
      
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - pandas
  - opencv
  - joblib
  - matplotlib-base
  - pyyaml
  - scikit-learn
  - nd2
  - pip
  - pip:
    - napari[all]